export const CREATE_BLOG_POST = 'CREATE_BLOG_POST';
export const CREATE_BLOG_POST_SUCCESS = 'CREATE_BLOG_POST_SUCCESS';
export const CREATE_BLOG_POST_FAILURE = 'CREATE_BLOG_POST_FAILURE';

export const GET_BLOG_POSTS = 'GET_BLOG_POSTS';
export const GET_BLOG_POSTS_SUCCESS = 'GET_BLOG_POSTS_SUCCESS';
export const GET_BLOG_POSTS_FAILURE = 'GET_BLOG_POSTS_FAILURE';

export const GET_BLOG_POST = 'GET_BLOG_POST';
export const GET_BLOG_POST_SUCCESS = 'GET_BLOG_POST_SUCCESS';
export const GET_BLOG_POST_FAILURE = 'GET_BLOG_POST_FAILURE';

export const UPDATE_BLOG_POST = 'UPDATE_BLOG_POST';
export const UPDATE_BLOG_POST_SUCCESS = 'UPDATE_BLOG_POST_SUCCESS';
export const UPDATE_BLOG_POST_FAILURE = 'UPDATE_BLOG_POST_FAILURE';

export const DELETE_BLOG_POST = 'DELETE_BLOG_POST';
export const DELETE_BLOG_POST_SUCCESS = 'DELETE_BLOG_POST_SUCCESS';
export const DELETE_BLOG_POST_FAILURE = 'DELETE_BLOG_POST_FAILURE';
