export const IMAGE_UPLOAD_REQUEST = 'IMAGE_UPLOAD_REQUEST'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_FAIL = 'IMAGE_UPLOAD_FAIL'

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST'
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS'
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL'

export const IMAGE_DETAILS_REQUEST = 'IMAGE_DETAILS_REQUEST'
export const IMAGE_DETAILS_SUCCESS = 'IMAGE_DETAILS_SUCCESS'
export const IMAGE_DETAILS_FAIL = 'IMAGE_DETAILS_FAIL'
export const IMAGE_DETAILS_CLEAR = 'IMAGE_DETAILS_CLEAR'
export const IMAGE_DETAILS_RESET = 'IMAGE_DETAILS_RESET'

export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS'
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL'
export const IMAGE_LIST_RESET = 'IMAGE_LIST_RESET'

export const IMAGE_UPDATE_REQUEST = 'IMAGE_UPDATE_REQUEST'
export const IMAGE_UPDATE_SUCCESS = 'IMAGE_UPDATE_SUCCESS'
export const IMAGE_UPDATE_FAIL = 'IMAGE_UPDATE_FAIL'
export const IMAGE_UPDATE_RESET = 'IMAGE_UPDATE_RESET'
